# Generated by Django 3.0.4 on 2020-04-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
