# Generated by Django 3.0.4 on 2020-04-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Prompt')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotator', models.CharField(max_length=100)),
                ('boundary', models.IntegerField()),
                ('tags', models.ManyToManyField(related_name='annotation_tags', to='core.Tag')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.EvaluationText')),
            ],
        ),
    ]
