# Generated by Django 3.0.4 on 2020-06-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
