# Generated by Django 3.0.4 on 2020-04-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_annotation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationtext',
            name='boundary',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
