# Generated by Django 3.0.4 on 2020-04-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200420_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='human',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
