# Generated by Django 3.0.7 on 2020-06-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200623_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='annotations',
        ),
        migrations.AddField(
            model_name='group',
            name='evaluation_texts',
            field=models.ManyToManyField(to='core.EvaluationText'),
        ),
    ]
